services:
  cisauth-db:
    image: postgres:latest
    restart: always
    container_name: cisauth-db
    env_file:
      - docker-compose-local.env
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/sql
      - cisauth-volume:/var/lib/postgresql/data/
    networks:
      - cisauth-network

  hydra-migrate:
    container_name: hydra-migrate
    image: oryd/hydra:v2.0.3
    command:
      migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./contrib/quickstart/${ENVIRONMENT}
        target: /etc/config/hydra
    restart: on-failure
    environment:
      - DSN=postgres://hydra:secret@cisauth-db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - cisauth-db
    networks:
      - cisauth-network

  hydra:
    container_name: hydra
    image: oryd/hydra:v2.0.3
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    volumes:
      - type: bind
        source: ./contrib/quickstart/${ENVIRONMENT}
        target: /etc/config/hydra
    command:
      serve -c /etc/config/hydra/hydra.yml all --dev
    restart: unless-stopped
    environment:
      - TTL_ACCESS_TOKEN=720h
      - TTL_ID_TOKEN=720h
      - DSN=postgres://hydra:secret@cisauth-db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SERVE_PUBLIC_CORS_ENABLED=true
      - SERVE_PUBLIC_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE
    depends_on:
      - cisauth-db
    networks:
      - cisauth-network

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - cisauth-network

  cisauth-cache:
    container_name: cisauth-cache
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server"]
    networks:
      - cisauth-network

  user-service:
    image: harishsivakumar/user-management-service:latest
    container_name: user-service
    platform: linux/amd64
    networks:
      - cisauth-network
    ports:
      - "8080:8080"
    depends_on:
      user-migrate:
        condition: service_completed_successfully
    volumes:
      - ./configs/user-config.json:/config/config.json
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  user-migrate:
    image: harishsivakumar/ums-migrate:latest
    container_name: ums-migrate
    platform: linux/amd64
    depends_on:
      - cisauth-db
    networks:
      - cisauth-network
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SECRET_KEY=dev/cisauth

  token-service:
    image: harishsivakumar/token-management-service:latest
    container_name: token-service
    depends_on:
      - cisauth-cache
    networks:
      - cisauth-network
    ports:
      - "5052:5052"
    volumes:
      - ./configs/token-config.json:/config/serviceconfig.json
    platform: linux/amd64
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  communication-service:
    image: harishsivakumar/customer-communication-service:latest
    container_name: communication-service
    depends_on:
      - cisauth-cache
    networks:
      - cisauth-network
    volumes:
      - ./configs/communication-config.json:/config/config.json
    platform: linux/amd64
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  frontend:
    image: harishsivakumar/cisauth-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - cisauth-network
    depends_on:
      - user-service
      - token-service
      - communication-service
    environment:
      - REACT_APP_OAUTH_REDIRECT_URI=https://www.cisauth.org/api/user-service/v1/login/accept
      - REACT_APP_PASSWORD_ENC_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFzcy9rQXJCWjNGTisyUVZ1bnUvSApobTRFNFMybnBDTG1UaGUvUnoyQVY5NFR5VmdFUUhXWE0vdFBuYXFQNCsveUR2RlhJNlBpbDNheFgvT2lyYlFnCm9Gam1xZ2w2Zm5NckJ2SlNqQXZ6aDlMQ081WU1yLzh1Z1hLTG55RlZaUi9aeE9SUFpPamlua3Y4UmFMcXE5bzIKdHBwNHN6R3FZaUFxQmpEb3BLVVEyeWtoZk9RTllFaXVvV09wMW1lQVExd0N0TXZTcFJ1U1k0MU41MG1oOFovcQpmbU9MTFBPQzBDYWVHZzBtdzdnUmhYd2ltU1Y0WjNtaGV0bnZtNVJCWHIxaEJYVXFDRXhRQmNkaHBLQnlIT3dTCml2YzVkcC9jRmtac3UwdUJvQXNIUHBraThxNUN2bUszMk1vZkNnWGxFQ01kMVI0OUhJTjBsbUtwN1VwVlRoQnoKWUp3T2d0eEthTk1EbHp4KzRKTWlxakxKOUFNT2V3N2NoODVjWGRvUGdRR0dmMmNOVjN4cEFWMEpDSmNTd2FIYQpGNUpSUW5md1VzdUdzalRoV1lvMVVrUVJxS1hXUVlGRmpYNFkzN29pNnJ5TEtTQWdOWUYyVnUzTGd5QWNoN2s4CmZJSWhqa2V1SWxtUFRYSGRXalR6T1ZtWEtseUx6Mmx2Z0MyWTg3NzVGZjlPZno5YndvdjlMK2VPSytTRSsweVAKeHR2TStGay9nMkhXT3UyUjk3Z1FuSUlPRDc3TUJVaXV4WDNodkh3VjZhWG01ZVdyNGtiVUVOWGRlY2cvS3VYZQozK0UzalNVaktFVkY2Wis0bG42R1djbzVrdDRtbFRKSS9CTjlWdW1Hc0tGd2JwZE1TRWprdUc3bU1qWHROWjVuCk5oR1A0bzN6K29CZ01URFBoWHViMmdVQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
      - REACT_APP_OAUTH_CLIENT_ID=a3c55263-1e63-4103-86d2-64ea63ddf17c
      - REACT_APP_OAUTH_URL=https://www.cisauth.org/
    platform: linux/amd64

networks:
  cisauth-network:
    external: true

volumes:
  cisauth-volume:
