version: '3.7'
services:

  build-env:
    image: golang:1.22-alpine3.19
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/imharish-sivakumar
    platform: linux/amd64
    volumes:
      - type: volume
        source: oauth2_clients_setup_dep
        target: /go
      - type: bind
        source: ../
        target: /oauth2-clients-setup
    working_dir: /oauth2-clients-setup

volumes:
  oauth2_clients_setup_dep:
