name: frontend
on: [ push ]
permissions:
  contents: read
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create env file
        run: |
          echo "REACT_APP_OAUTH_REDIRECT_URI=${{ secrets.REACT_APP_OAUTH_REDIRECT_URI }}" >> ./frontend/.env
          echo "REACT_APP_PASSWORD_ENC_PUBLIC_KEY=${{ secrets.REACT_APP_PASSWORD_ENC_PUBLIC_KEY }}" >> ./frontend/.env
          echo "REACT_APP_OAUTH_CLIENT_ID=${{ secrets.REACT_APP_OAUTH_CLIENT_ID }}" >> ./frontend/.env
          echo "REACT_APP_OAUTH_URL=${{ secrets.REACT_APP_OAUTH_URL }}" >> ./frontend/.env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          tags: harishsivakumar/cisauth-frontend:latest
